pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        flatDir {
            dirs 'android/mm-ad-sdk'
        }
    }
}

rootProject.name = "routerkeygenAndroid"
include ':routerKeygen'
include ':aFileChooser'
project(':routerKeygen').projectDir = new File(rootDir, 'android/routerKeygen/')
project(':aFileChooser').projectDir = new File(rootDir, 'android/aFileChooser/')
