plugins {
    id 'com.android.library'
}

android {
    namespace 'com.ipaulpro.afilechooser'
    compileSdk 36

    defaultConfig {
        minSdk 28
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
}